--- 
- name: Install and Configure Tomat 
  hosts: all
  become: yes
  gather_facts: false
  vars_files: secret.yaml
  vars:
    nexus_repository_url: "http://35.209.45.241:8081/repository/maven-snapshots"
  tasks:
    - name: Install lxml
      apt:
        name: python3-lxml
        state: present 
    - name: "Download war the file"
      maven_artifact:
        group_id: api1
        artifact_id: api1
        version: 0.0.1-SNAPSHOT
        extension: war
        repository_url: "{{ nexus_repository_url }}"
        username: "admin"
        password: "{{ password }}"
        dest: "/opt/tomcat/webapps/simple-app.war"
        mode: '0644'

    - name: Reload and Start the Tomcat service
      systemd:
        daemon_reload: true
        name: tomcat 
        state: started
        enabled: true 

    - name: Check the status of Tomcat service
      shell: systemctl status tomcat
      register: tomcat
      notify: tomcat-service

  handlers:
    - name: tomcat-service
      debug:
        var: tomcat.stdout_lines
